function init -a path --on-event init_git
  set -U fish_user_abbreviations 'g=git'
  set fish_user_abbreviations $fish_user_abbreviations 'ga=git add'
  set fish_user_abbreviations $fish_user_abbreviations 'gaa=git add --all :/'
  set fish_user_abbreviations $fish_user_abbreviations 'gb=git branch'
  set fish_user_abbreviations $fish_user_abbreviations 'gbd=git branch -d'
  set fish_user_abbreviations $fish_user_abbreviations 'gc=git commit'
  set fish_user_abbreviations $fish_user_abbreviations 'gco=git checkout'
  set fish_user_abbreviations $fish_user_abbreviations 'gcm=git commit -am'
  set fish_user_abbreviations $fish_user_abbreviations 'gcf=git config'
  set fish_user_abbreviations $fish_user_abbreviations 'gclean=git reset --hard && git clean -dfx'
  set fish_user_abbreviations $fish_user_abbreviations 'gd=git diff'
  set fish_user_abbreviations $fish_user_abbreviations 'gl=git log'
  set fish_user_abbreviations $fish_user_abbreviations 'glg=git log --stat --max-count=10'
  set fish_user_abbreviations $fish_user_abbreviations 'glgg=git log --graph --max-count=10'
  set fish_user_abbreviations $fish_user_abbreviations 'glgga=git log --graph --decorate --all'
  set fish_user_abbreviations $fish_user_abbreviations 'glo=git log --oneline --decorate --color'
  set fish_user_abbreviations $fish_user_abbreviations 'glog=git log --oneline --decorate --color --graph'
  set fish_user_abbreviations $fish_user_abbreviations 'gm=git merge'
  set fish_user_abbreviations $fish_user_abbreviations 'gp=git push'
  set fish_user_abbreviations $fish_user_abbreviations 'gpu=git pull'
  set fish_user_abbreviations $fish_user_abbreviations 'gs=git status'
  set fish_user_abbreviations $fish_user_abbreviations 'gst=git status'
  set fish_user_abbreviations $fish_user_abbreviations 'gu=git pull'
  
  # hub
  set fish_user_abbreviations $fish_user_abbreviations 'gbr=git browse'
  set fish_user_abbreviations $fish_user_abbreviations 'gcmp=git compare'
  set fish_user_abbreviations $fish_user_abbreviations 'gfk=git fork'
  set fish_user_abbreviations $fish_user_abbreviations 'gprq=git pull-request'
end

