import $plugin.$ivy.`org.typelevel::kind-projector:0.10.3`
import $ivy.`org.typelevel::cats-core:2.1.1`
import $ivy.`com.chuusai::shapeless:2.3.3`
import $ivy.`io.circe::circe-core:0.13.0`
import $ivy.`io.circe::circe-generic:0.13.0`
import $ivy.`co.fs2::fs2-core:2.4.4`
import cats._
import shapeless._
import cats.data._
import cats.syntax.all._
import cats.instances.all._
