abbr -a -U -- dc docker-compose
abbr -a -U -- drmio 'docker rmi (docker images -q -f dangling=true)'
abbr -a -U -- em emacsclient
abbr -a -U -- ga 'git add'
abbr -a -U -- gbd 'git branch -d'
abbr -a -U -- gb 'git branch'
abbr -a -U -- gbr 'git browse'
abbr -a -U -- gcf 'git config'
abbr -a -U -- gc 'git commit'
abbr -a -U -- gclean 'git reset --hard && git clean -dfx'
abbr -a -U -- gcm 'git commit -am'
abbr -a -U -- gcmp 'git compare'
abbr -a -U -- gco 'git checkout'
abbr -a -U -- gd 'git diff'
abbr -a -U -- gfk 'git fork'
abbr -a -U -- g git
abbr -a -U -- glgga 'git log --graph --decorate --all'
abbr -a -U -- glgg 'git log --graph --max-count 10'
abbr -a -U -- glg 'git log --stat --max-count 10'
abbr -a -U -- gl 'git log'
abbr -a -U -- glog 'git log --oneline --decorate --color --graph'
abbr -a -U -- glo 'git log --oneline --decorate --color'
abbr -a -U -- gm 'git merge'
abbr -a -U -- gp 'git push'
abbr -a -U -- gpom 'git pull origin master'
abbr -a -U -- gprq 'git pull-request'
abbr -a -U -- gpu 'git pull'
abbr -a -U -- gs 'git status'
abbr -a -U -- gst 'git status'
abbr -a -U -- gu 'git pull'
abbr -a -U -- kbcr 'kubectl --namespace="platform-reliability"'
