abbr dc 'docker compose'
abbr em emacsclient
abbr g git
abbr ga 'git add'
abbr gb 'git branch'
abbr gbd 'git branch -d'
abbr gbr 'git browse'
abbr gc 'git commit'
abbr gcf 'git config'
abbr gclean 'git reset --hard && git clean -dfx'
abbr gcm 'git commit -am'
abbr gcmp 'git compare'
abbr gco 'git checkout'
abbr gd 'git diff'
abbr gfk 'git fork'
abbr gl 'git log'
abbr glg 'git log --stat --max-count 10'
abbr glgg 'git log --graph --max-count 10'
abbr glgga 'git log --graph --decorate --all'
abbr glo 'git log --oneline --decorate --color'
abbr glog 'git log --oneline --decorate --color --graph'
abbr gm 'git merge'
abbr gp 'git push'
abbr gpom 'git pull origin master'
abbr gprq 'git pull-request'
abbr gpu 'git pull'
abbr gs 'git status'
abbr gst 'git status'
abbr gu 'git pull'
